Provide admins with a way to regenerate their API token
DMPRoadmap/roadmap pull request #2718
Opened 2020-11-06 18:14 UTC by briri

Fixes #2410 .

Added ability for user to regenerate their own API token (or create one if it was not initialized for some reason when they became an Org admin). Also updated the application.js to make jQuery and the notificationHelper functions available within the js.erb files.

Changes proposed in this PR:
- Move API token and link to wiki documentation to its own tab on Edit Profile page
- Update initializer to provide both v0 and v1 API urls
- Add a 'Regenerate token' button to new tab and brief explanation of v0 and v1 with links to their wiki pages
- Add route, controller and js.erb to regerate the user's token
- Update User model to separate out the create token functionality from the create_or_update method
- Update the application.js to make jQuery and the renderNotice and renderAlert helper functions available to the js.erb files
- Update api_client credentials mailer to use updated initializer values
- Update the refresh api client credentials js.erb

2020-11-10 10:02 UTC, xsrust requested changes

2020-11-10 10:02 UTC, xsrust commented on app/views/super_admin/api_clients/email_credentials.js.erb
> +renderNotice(msg);
Great to see these TODO's going away:)

2020-11-10 16:26 UTC, briri commented on app/policies/user_policy.rb
> +  end
Yes, the button should not appear unless they're an Org admin but it would make sense to add logic to the policy

2020-11-10 16:44 UTC, briri commented
Ok @xsrust I added some permission checks to that policy

2020-11-11 09:37 UTC, xsrust approved these changes
Thanks for updating

2020-11-11 09:37 UTC, merged