fix section sort
DMPRoadmap/roadmap pull request #2735
Opened 2020-11-19 17:15 UTC by nicolasfranck

What it tries to fix: if you, in the org-admin, try to move the section headers, you'll get a javascript in the console.

Fix:

* `$.rails.ajax` should use option `type`, not `method`
* controller `OrgAdmin::PhasesController#sort` expects `phase[sort_order]`, not just `sort_order`
* concern incorrectly converted array of ids into array of arrays by prepending ids with a star.

2020-11-19 17:54 UTC, briri requested changes
looks good @nicolasfranck. Just make that one small change and we will be good 👍

2020-11-19 17:54 UTC, briri commented on app/javascript/src/orgAdmin/phases/show.js
> +        $.param({ 'phase[sort_order]': sectionIds }),
I think you're missing `data: ` here. I receive a JS error with the above

2020-11-19 21:40 UTC, nicolasfranck commented
Fixed.

Btw, how did you manage to merge in your development branch into my branch?

See https://github.com/DMPRoadmap/roadmap/pull/2735/commits/11d95923b05f988a42d12f8b5064168d9cc682ce

2020-11-19 23:07 UTC, briri commented
sorry about that! GitHub has a 'Update branch' button that shows up when the branch being PRed isn't up to date. Its a bit dangerous I guess since it updates a repo I am not a member of!

2020-11-24 10:26 UTC, xsrust commented
I'm additionally updating this branch, see https://github.com/DMPRoadmap/roadmap/pull/2741#issuecomment-732804820 for an explanation

2020-11-25 16:13 UTC, briri reviewed
looks good. thanks

2020-11-25 16:13 UTC, briri approved these changes

2020-11-25 16:13 UTC, merged

2020-12-16 14:45 UTC, pherterich commented
Assuming that this is about dragging template sections around, that is working for me.