Remove vulnerability xss hack
DMPRoadmap/roadmap pull request #3030
Opened 2021-09-19 22:36 UTC by martaribeiro

Fixes # https://github.com/DigitalCurationCentre/DMPonline-Service/issues/603.

Changes proposed in this PR:
Callback was added to user and plan models. 'before_save' was added with a function sanitise a number of field before data was saved into the db
-

2021-09-21 15:04 UTC, briri requested changes
Thanks for tackling this one @martaribeiro.

I think it would good to move this into the base application_record.rb file that all of the models inherit from. Something like:
```ruby
class ApplicationRecord < ActiveRecord::Base

   #  other existing methods

   def sanitize_fields(*attrs)
     attrs.each do |attr| 
       self.send("#{attr.to_s}=", ActionController::Base.helpers.sanitize(self.send(attr)))
     end
   end
```
Then, in the models you can do something like:
`before_save sanitize_fields(:title, :funder_name, :grant_number, :identifier, :description)`

2021-09-27 16:56 UTC, briri approved these changes

2021-09-27 16:56 UTC, briri commented
was out of sync with development so rebased via GitHub

2021-09-27 20:10 UTC, merged

2022-12-05 14:56 UTC, Karimblack commented
">]<img src=x onerror=alert(document.domain)> ">]<img src=x onerror=alert(document.cookie)>