Added toggleable guidance/comments section
DMPRoadmap/roadmap pull request #3123
Opened 2022-03-08 10:36 UTC by benjaminfaure

Changes proposed in this PR:

- Add toggleable comments/guidance section
  - add config to enable/disable this feature
  - add config to open/close by default
  - question/guidance divs use flexbox instead of bootstrap grid system

2022-03-08 10:37 UTC, benjaminfaure commented
I wasn't sure where to put the CSS & JS code, if it's in the wrong place please tell me :)

2022-03-08 15:58 UTC, briri requested changes
Thanks for getting this to us so quickly @benjaminfaure!

I have 2 very minor changes. It looks great overall and the JS and SCSS files are in the correct place! :)

I will pull down the changes and confirm that it works as expected in the UI later today

2022-03-08 15:58 UTC, briri commented on config/initializers/_dmproadmap.rb
> +    config.x.application.guidance_comments_opened = true
Can you change the name of this variable to `guidance_comments_opened_by_default`?

2022-03-09 07:05 UTC, benjaminfaure commented
Thanks for your feedback @briri , I push the changes you requested :)

2022-03-11 11:28 UTC, raycarrick-ed commented
@benjaminfaure @briri Pulled down the code on top of an up to date roadmap and it worked perfectly out of the box. Very nice! So I'm for it to get merged in.

2022-03-11 15:22 UTC, briri approved these changes

2022-03-11 15:23 UTC, merged